tboxhome=pwd;
addpath([pwd,'/3dRobotArm/'],[pwd,'/analysis/'],...
  [pwd,'/learning/'],[pwd,'/acquisition/'],[pwd,'/ftrating/'],...
  [pwd,'/super/'],[pwd,'/acquisition/emo-logger'],...
  [pwd,'/acquisition/nk-logger'],[pwd,'/acquisition/nk-ui']);
savepath;
